[tool.poetry]
description = "Generate continuous time stationary stochastic processes from a given auto correlation function."
name = "stocproc"
version = "1.1.2"
authors = ["Richard Hartmann <richard.hartmann@tu-dresden.de>"]
license = "BSD (3 clause)"
classifiers = [
"Operating System :: OS Independent",
"License :: OSI Approved :: BSD License",
"Topic :: Utilities",
"Intended Audience :: Researcher"
]
repository = "https://github.com/cimatosa/stocproc"
build = 'build.py'

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
scipy = "^1.7.3"
mpmath = "^1.3.0"
fcSpline = { git = "https://github.com/vale981/fcSpline" }
numpy = "^1.22.2"

[tool.poetry.dev-dependencies]
setuptools = "^59.5.0"
Cython = "^0.29.25"
black = "^21.12b0"

[build-system]
requires = ["poetry>=0.12", "cython", "setuptools", "numpy"]
build-backend = "poetry.core.masonry.api"
